### ISSUE TITLE
Erro na função fopen

### ISSUE THREAD

**Issue by jeffersono7** [jeffersono7/apc#1]
Erro na função fopen(), programa fecha retornando erro.

**Comment by jeffersono7** [comment]
corrigido!

**Comment by weslley17w** [comment]
Qual era o erro ?

**Comment by jeffersono7** [comment]
Para abrir usando 'a' e seria "a", pra mim q em c++ usava 'a' mas quem sabe
neh
Em 22/11/2016 15:47, "Weslley Barros" notifications@github.com escreveu:

**Comment by jeffersono7** [comment]
Corrigi outras coisas tbm kkkk. Temos que ver dps a parte do gets. Podemos
usar fflush e dps fprintf(stdin)
Em 22/11/2016 16:37, "Jefferson oliveira farias" <
jefferson.farias7@gmail.com> escreveu:

**Comment by jeffersono7** [comment]
Fscanf na vdd. Tá ficando legal
Em 22/11/2016 16:49, "Jefferson oliveira farias" <
jefferson.farias7@gmail.com> escreveu:
