### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jeffersono7** [jeffersono7/apc#7]
-leitura->Caso tentar abrir arquivo em modo leitura e ele não existir-> fecha com erro.
-relatório_individual->Caso tenha dois nomes iguais cadastrados-> exibirá o primeiro que encontrar.

**Comment by jeffersono7** [comment]
-leitura: Corrigido

**Comment by weslley17w** [comment]
New bug: 

erro hora de apresentar char no relatório individual.

**Comment by weslley17w** [comment]
Agora temos o relatório geral, como nos vamos prosseguir?.

**Comment by jeffersono7** [comment]
temos que receber a opcao de nivel, para exibir de acordo com o nível os cadastros. Vamos adicionar isso em relatorio_geral, if(nivel==nivel_digitado) { exibe cadastro_da_posicao }, mais ou menos isso, falta alguma outra coisa que o prof pediu?

**Comment by weslley17w** [comment]
não, so isso nos pode aproveitar os print do individual, da uma olhada no
bug do print que eu enviei.


Em 25 de novembro de 2016 21:53, jeffersono7 <notifications@github.com>
escreveu:

**Comment by jeffersono7** [comment]
falta corrigir a parte dos acentos, o setlocale está funcionando, aparentemente o erro está pq usei linux para criar boa parte do código, usando caracteres diferentes do windows, por padrão.

**Comment by jeffersono7** [comment]
Todos os erros corrigidos!
